Implement Interaction Button
AUSG/2022-homepage pull request #91
Opened 2023-08-28 17:29 UTC by grayashh

# Summary
#56 
- joey는 notion에만 적용이 가능한걸로 확인되었습니다. 
- 따라서 lyket ( 500 views / per month)을 커스텀하여 대문에 적용하였습니다.
- 호버 시 클라우드 모양 이모티콘의 scale이 커지도록 transition을 주었습니다.
- 클릭 시 클라우드 이모티콘이 바뀌며 count가 늘어납니다. 다시 한번 클릭 시 원상복구 됩니다.

## 인터랙션 블록 클릭 전
![image](https://github.com/AUSG/2022-homepage/assets/49053676/1e476d05-052a-4921-9359-65ec87639833)

## 인터랙션 블록 클릭 시
![image](https://github.com/AUSG/2022-homepage/assets/49053676/e573c71b-e700-4fc4-979e-c6d7a61cb6ee)

2023-08-28 20:18 UTC, Yaminyam commented
pr 본문에서 issue를 언급할때 close, resolve, fix 와 같은 키워드로 연결해주시면 좋을것 같습니다.
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

2023-08-29 02:43 UTC, grayashh commented
> pr 본문에서 issue를 언급할때 close, resolve, fix 와 같은 키워드로 연결해주시면 좋을것 같습니다. https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

issue link 방법에 대해 숙지하지 못했었네요,,!! 수정했습니다👍

2023-08-29 15:47 UTC, roeniss requested changes
와 진짜 수고하셨습니다!!!!

> joey는 notion에만 적용이 가능한걸로 확인되었습니다.

헉 몰랐네요;; 시간 쓰셨겠네요 감사합니다 :bow:

호버도 너무 멋지네요 ㅠㅠ

--

Q. lyket 쪽에 따로 계정을 만드셨나요? 그렇다면 ausg 계정으로 하는게 나을 것 같습니다.

2023-08-29 15:47 UTC, roeniss commented on src/_pages/index/components/IntroSection.tsx
> +              <Provider apiKey="pt_5a9c4059fce90df5f406e6b77045c0 ">
그런데 api key 가 public 이어도 되는건 좀 의아하네요 (태강님에게 드리는 리뷰는 아니고 그냥 그 자체로 이상함). 다른 서버에서 api key 사용하면 내 quota 뺏기는거 아닌가? 아니면 lyket 쪽에서 도메인 세팅을 따로 해주는건가? :thinking:

2023-08-29 15:47 UTC, roeniss commented on src/_pages/index/components/IntroSection.tsx
> +                    <div className="mt-[24px] flex flex-row items-center justify-center gap-4 text-white md:min-w-[400px] md:flex-1">
이 PR 외의 위쪽에서 다른 룰이 보이는 것 같은데요, 

```
          <div className="mt-[8px] flex flex-col items-center md:min-w-[400px] md:flex-1">
```

css 를 동일하게 가져가지 않는것이 의도인가요?

2023-08-29 15:49 UTC, roeniss commented
@grayashh  키는 `pt_42fe46c843e030ddadfb059b67c6dd` 로 교체해주세요! 제가 ausg 지메일로 발급했습니다. (secret key 는 필요한지 잘 모르겠지만 일단 슬랙 DM 으로 드리겠습니다). 미리 전달드리지 못해 죄송합니다!

2023-08-29 15:49 UTC, roeniss commented on src/_pages/index/components/IntroSection.tsx
> +              <Provider apiKey="pt_5a9c4059fce90df5f406e6b77045c0 ">
아 그렇네요 따로 세팅하네요 ㅋㅋ

2023-08-29 15:53 UTC, grayashh commented on src/_pages/index/components/IntroSection.tsx
> +              <Provider apiKey="pt_5a9c4059fce90df5f406e6b77045c0 ">
네ㅎㅎㅎ 자체적으로 도메인을 받아서 CORS를 세팅해주더라구요! 제가 추가적으로 적었어야 했는데,,! 놓쳤네요🥹

2023-08-29 15:57 UTC, grayashh commented on src/_pages/index/components/IntroSection.tsx
> +                    <div className="mt-[24px] flex flex-row items-center justify-center gap-4 text-white md:min-w-[400px] md:flex-1">
이 부분은 레이아웃을 잡기 위해서 css를 비슷하게 가져와 marginTopr과 flex-direction을 변경해서 세팅했습니다..!
사실 중복되는 부분이 많은데 제거하지 않은 것 같아서
`<div className="mt-[24px] flex items-center gap-4">`
아래 코드로 변경하도록 하겠습니다~!

2023-08-29 15:58 UTC, roeniss commented on src/_pages/index/components/IntroSection.tsx
> +                    <div className="mt-[24px] flex flex-row items-center justify-center gap-4 text-white md:min-w-[400px] md:flex-1">
아하. 알겠습니다! 저는 css 를 몰라서 가볍게 던진 질문이니 알아서 걸러들어주세용

2023-08-29 15:58 UTC, grayashh commented
> @grayashh 키는 `pt_42fe46c843e030ddadfb059b67c6dd` 로 교체해주세요! 제가 ausg 지메일로 발급했습니다. (secret key 는 필요한지 잘 모르겠지만 일단 슬랙 DM 으로 드리겠습니다). 미리 전달드리지 못해 죄송합니다!

네 확인했습니다~!!

2023-08-29 16:05 UTC, roeniss approved these changes
머지하시죠! 수고하셨습니다 @grayashh

2023-08-29 16:07 UTC, grayashh commented
> 머지하시죠! 수고하셨습니다 @grayashh

정성스런 리뷰 감사드립니당,,,,!🙇‍♂️

2023-08-29 16:07 UTC, merged